build:
    bazel build //...

test:
    bazel test --test_output=errors //...

hedron:
    bazel run @hedron_compile_commands//:refresh_all

tidy:
    bazel build //... \
      --aspects @bazel_clang_tidy//clang_tidy:clang_tidy.bzl%clang_tidy_aspect \
      --output_groups=report \
      --verbose_failures
