load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

##############
# Clang Tidy #
##############
load(
    "@bazel_tools//tools/build_defs/repo:git.bzl",
    "git_repository",
)

git_repository(
       name = "bazel_clang_tidy",
       commit = "bff5c59c843221b05ef0e37cef089ecc9d24e7da",
       remote = "https://github.com/erenon/bazel_clang_tidy.git",
)

## ranges-v3
http_archive(
    name = "ranges-v3",
    sha256 = "015adb2300a98edfceaf0725beec3337f542af4915cec4d0b89fa0886f4ba9cb",
    strip_prefix = "range-v3-0.12.0",
    urls = [
        "https://github.com/ericniebler/range-v3/archive/refs/tags/0.12.0.tar.gz",
    ],
)

http_archive(
    name = "tartanllama_expected",
    build_file = "//third_party:tartanllama_expected.BUILD",
    urls = ["https://github.com/TartanLlama/expected/archive/refs/tags/v1.1.0.tar.gz"],
    strip_prefix = "expected-1.1.0",
)

http_archive(
    name = "tartanllama_optional",
    build_file = "//third_party:tartanllama_optional.BUILD",
    urls = ["https://github.com/TartanLlama/optional/archive/refs/tags/v1.1.0.tar.gz"],
    strip_prefix = "optional-1.1.0",
)
