load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

##############
# Clang Tidy #
##############
load(
    "@bazel_tools//tools/build_defs/repo:git.bzl",
    "git_repository",
)

git_repository(
       name = "bazel_clang_tidy",
       commit = "bff5c59c843221b05ef0e37cef089ecc9d24e7da",
       remote = "https://github.com/erenon/bazel_clang_tidy.git",
)
