query:
    bazel query //file_operations:all

show_files:
    # Corresponds to DefaultInfo.files?
    bazel cquery --output=files //file_operations:bar

build:
    bazel build //... --//file_operations:extension=log
