name: bayes
channels:
  - conda-forge
dependencies:
  - altair
  - altair-viewer
  - conda-build
  - conda-lock
  - ipython
  - jupyterlab
  - jupytext
  - scikit-learn
  - pandas
  - pip
  - pymc
  - pyright
  - python=3.11
  - vega_datasets
  - pip:
    - black
    - bokeh
    - flake8
    - graphviz
    - streamlit
