name: bayes
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-build
  - conda-lock
  - ipython>=8
  - jupyterlab>=4
  - jupytext>=1
  - numpy==1.24.3
  - pandas==2.0.2
  - pip>=23
  - scikit-learn>=1
  - pymc>=5
  - pyright>=1.1.316
  - python==3.11.3
  - pip:
    - altair
    - altair_viewer
    - black
    - bokeh
    - flake8
    - graphviz
    - streamlit
    - vega_datasets
