repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.1
  hooks:
  # Run the linter.
  - id: ruff
    types_or: [ python, pyi ]
    args: [ --fix ]
  # Run the formatter.
  - id: ruff-format
    types_or: [ python, pyi ]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.8
  hooks:
  - id: clang-format
- repo: https://github.com/doublify/pre-commit-rust
  rev: master
  hooks:
  - id: fmt
  - id: cargo-check
