dev:
    dg dev

jobA:
    echo "# Executing job" | glow -
    dg launch --job jobA

jobB:
    echo "# Executing job" | glow -
    dg launch --job jobB

test-job:
    uv run pytest -s tests/

docker-build:
    docker build . -t vinh_dagster_playground:latest

docker-run:
    docker run --rm -it vinh_dagster_playground:latest /bin/sh
