[project]
name = "k8s"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cdk8s>=2.70.15",
]

[dependency-groups]
dev = [
    "ipython>=9.5.0",
    "pyright>=1.1.405",
    "ruff>=0.13.0",
]
