cc_library(
    name = "build_error_tester",
    hdrs = ["build_error_tester.h"],
    deps = []
)

cc_test(
    name = "build_error_tester_test",
    srcs = ["build_error_tester.cc"],
    deps = [
        ":build_error_tester",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ]
)
