cc_library(name = "sfinae", srcs = ["sfinae.cc"], hdrs = ["sfinae.h"],
           visibility = ["//visibility:public"], )

    cc_library(name = "templates", srcs = ["templates.cc"],
               hdrs = ["templates.h"], visibility = ["//visibility:public"], )
