cc_test(
    name = "ranges_test",
    srcs = ["ranges_test.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ]
)

cc_test(
    name = "ranges_types_test",
    srcs = ["ranges_types_test.cc"],
    deps = [
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ]
)
