name: iso
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-build
  - conda-lock
  - ipython>=8
  - pip>=23
  - pyright>=1.1.316
  - python==3.11.3
  - pip:
    - black
    - factory-boy
    - fastapi[all]
    - flake8
